export const INITIAL_GAINS = {
  stcg: {
    profits: 100,
    losses: 500,
  },
  ltcg: {
    profits: 1200,
    losses: 100,
  }
};

export const MOCK_ASSETS = [
  {
    id: '1',
    name: 'Bitcoin',
    symbol: 'BTC',
    icon: 'https://static.coinpaprika.com/coin/btc-bitcoin/logo.png',
    holdings: 0.12,
    price: 64230.50,
    value: 7707.66,
    shortTermPerformance: -850,
    longTermPerformance: 0,
    type: 'ST'
  },
  {
    id: '2',
    name: 'Ethereum',
    symbol: 'ETH',
    icon: 'https://static.coinpaprika.com/coin/eth-ethereum/logo.png',
    holdings: 2.5,
    price: 3450.20,
    value: 8625.50,
    shortTermPerformance: 500,
    longTermPerformance: -1000,
    type: 'LT'
  },
  {
    id: '3',
    name: 'Polygon',
    symbol: 'MATIC',
    icon: 'https://static.coinpaprika.com/coin/matic-polygon/logo.png',
    holdings: 5000,
    price: 0.72,
    value: 3600,
    shortTermPerformance: -350,
    longTermPerformance: 0,
    type: 'ST'
  },
  {
    id: '4',
    name: 'Solana',
    symbol: 'SOL',
    icon: 'https://static.coinpaprika.com/coin/sol-solana/logo.png',
    holdings: 45,
    price: 145.50,
    value: 6547.50,
    shortTermPerformance: 0,
    longTermPerformance: -1200,
    type: 'LT'
  },
  {
    id: '5',
    name: 'Cardano',
    symbol: 'ADA',
    icon: 'https://static.coinpaprika.com/coin/ada-cardano/logo.png',
    holdings: 2500,
    price: 0.45,
    value: 1125,
    shortTermPerformance: -150,
    longTermPerformance: 0,
    type: 'ST'
  },
  {
    id: '6',
    name: 'XRP',
    symbol: 'XRP',
    icon: 'https://static.coinpaprika.com/coin/xrp-xrp/logo.png',
    holdings: 1000,
    price: 0.62,
    value: 620,
    shortTermPerformance: 50,
    longTermPerformance: -200,
    type: 'LT'
  },
  {
    id: '7',
    name: 'Dogecoin',
    symbol: 'DOGE',
    icon: 'https://static.coinpaprika.com/coin/doge-dogecoin/logo.png',
    holdings: 10000,
    price: 0.16,
    value: 1600,
    shortTermPerformance: -400,
    longTermPerformance: 0,
    type: 'ST'
  },
  {
    id: '8',
    name: 'Tron',
    symbol: 'TRX',
    icon: 'https://static.coinpaprika.com/coin/trx-tron/logo.png',
    holdings: 15000,
    price: 0.11,
    value: 1650,
    shortTermPerformance: 0,
    longTermPerformance: -150,
    type: 'LT'
  },
  {
    id: '9',
    name: 'Chainlink',
    symbol: 'LINK',
    icon: 'https://static.coinpaprika.com/coin/link-chainlink/logo.png',
    holdings: 120,
    price: 18.20,
    value: 2184,
    shortTermPerformance: -250,
    longTermPerformance: 0,
    type: 'ST'
  },
  {
    id: '10',
    name: 'Polkadot',
    symbol: 'DOT',
    icon: 'https://static.coinpaprika.com/coin/dot-polkadot/logo.png',
    holdings: 300,
    price: 8.50,
    value: 2550,
    shortTermPerformance: 0,
    longTermPerformance: -450,
    type: 'LT'
  },
  {
    id: '11',
    name: 'Avalanche',
    symbol: 'AVAX',
    icon: 'https://static.coinpaprika.com/coin/avax-avalanche/logo.png',
    holdings: 50,
    price: 45.30,
    value: 2265,
    shortTermPerformance: -320,
    longTermPerformance: 0,
    type: 'ST'
  },
  {
    id: '12',
    name: 'Shiba Inu',
    symbol: 'SHIB',
    icon: 'https://static.coinpaprika.com/coin/shib-shiba-inu/logo.png',
    holdings: 10000000,
    price: 0.000025,
    value: 250,
    shortTermPerformance: 0,
    longTermPerformance: -80,
    type: 'LT'
  },
  {
    id: '13',
    name: 'Litecoin',
    symbol: 'LTC',
    icon: 'https://static.coinpaprika.com/coin/ltc-litecoin/logo.png',
    holdings: 15,
    price: 85.40,
    value: 1281,
    shortTermPerformance: -120,
    longTermPerformance: 0,
    type: 'ST'
  },
  {
    id: '14',
    name: 'Bitcoin Cash',
    symbol: 'BCH',
    icon: 'https://static.coinpaprika.com/coin/bch-bitcoin-cash/logo.png',
    holdings: 5,
    price: 480.20,
    value: 2401,
    shortTermPerformance: 0,
    longTermPerformance: -350,
    type: 'LT'
  },
  {
    id: '15',
    name: 'Uniswap',
    symbol: 'UNI',
    icon: 'https://static.coinpaprika.com/coin/uni-uniswap/logo.png',
    holdings: 200,
    price: 12.10,
    value: 2420,
    shortTermPerformance: -180,
    longTermPerformance: 0,
    type: 'ST'
  },
  {
    id: '16',
    name: 'NEAR Protocol',
    symbol: 'NEAR',
    icon: 'https://static.coinpaprika.com/coin/near-near-protocol/logo.png',
    holdings: 400,
    price: 6.80,
    value: 2720,
    shortTermPerformance: 0,
    longTermPerformance: -420,
    type: 'LT'
  },
  {
    id: '17',
    name: 'Dai',
    symbol: 'DAI',
    icon: 'https://static.coinpaprika.com/coin/dai-dai/logo.png',
    holdings: 1000,
    price: 1.00,
    value: 1000,
    shortTermPerformance: -5,
    longTermPerformance: 0,
    type: 'ST'
  },
  {
    id: '18',
    name: 'Injective',
    symbol: 'INJ',
    icon: 'https://static.coinpaprika.com/coin/inj-injective/logo.png',
    holdings: 80,
    price: 32.50,
    value: 2600,
    shortTermPerformance: 0,
    longTermPerformance: -380,
    type: 'LT'
  },
  {
    id: '19',
    name: 'Pepe',
    symbol: 'PEPE',
    icon: 'https://static.coinpaprika.com/coin/pepe-pepe/logo.png',
    holdings: 100000000,
    price: 0.000008,
    value: 800,
    shortTermPerformance: -150,
    longTermPerformance: 0,
    type: 'ST'
  },
  {
    id: '20',
    name: 'Optimism',
    symbol: 'OP',
    icon: 'https://static.coinpaprika.com/coin/op-optimism/logo.png',
    holdings: 600,
    price: 3.20,
    value: 1920,
    shortTermPerformance: 0,
    longTermPerformance: -220,
    type: 'LT'
  },
  {
    id: '21',
    name: 'Arbitrum',
    symbol: 'ARB',
    icon: 'https://static.coinpaprika.com/coin/arb-arbitrum/logo.png',
    holdings: 1200,
    price: 1.45,
    value: 1740,
    shortTermPerformance: -310,
    longTermPerformance: 0,
    type: 'ST'
  },
  {
    id: '22',
    name: 'Aptos',
    symbol: 'APT',
    icon: 'https://static.coinpaprika.com/coin/apt-aptos/logo.png',
    holdings: 150,
    price: 14.20,
    value: 2130,
    shortTermPerformance: 0,
    longTermPerformance: -190,
    type: 'LT'
  },
  {
    id: '23',
    name: 'Stacks',
    symbol: 'STX',
    icon: 'https://static.coinpaprika.com/coin/stx-stacks/logo.png',
    holdings: 500,
    price: 3.10,
    value: 1550,
    shortTermPerformance: -240,
    longTermPerformance: 0,
    type: 'ST'
  },
  {
    id: '24',
    name: 'Immutable',
    symbol: 'IMX',
    icon: 'https://static.coinpaprika.com/coin/imx-immutable/logo.png',
    holdings: 400,
    price: 2.80,
    value: 1120,
    shortTermPerformance: 0,
    longTermPerformance: -130,
    type: 'LT'
  },
  {
    id: '25',
    name: 'Cosmos',
    symbol: 'ATOM',
    icon: 'https://static.coinpaprika.com/coin/atom-cosmos/logo.png',
    holdings: 180,
    price: 10.50,
    value: 1890,
    shortTermPerformance: -210,
    longTermPerformance: 0,
    type: 'ST'
  }
];
